### ISSUE TITLE
Cannot install packages via pnpm within a container environment

### ISSUE THREAD

**Issue by pchaganti** [awslabs/green-boost#178] opened 2023-03-06 13:22 UTC
Trying out gboost in a container. Currently running ```pnpm i``` results in an error. This is probably not a gboost issue, but something to be aware of. If anyone has tried this and has a workaround, would love to know.

Created an issue in pnpm repo for tracking this as well - https://github.com/pnpm/pnpm/issues/6187

**Comment by bestickley** [comment] 2023-03-06 14:11
@pchaganti, thanks for reporting. Is this issue with `gboost` limited to the container for you? I'm not able to reproduce but I will stay on the lookout.

**Comment by pchaganti** [comment] 2023-03-06 14:29
My use case is primarily running in vscode devcontainers. Have not tried it other env.

thanks!

**Comment by bestickley** [comment] 2023-05-22 20:24
@pchaganti, I'm going to close this issue as I think this is more of an issue with the VSCode Dev Container. Feel free to reopen if that's not the case.

**Closed by bestickley** 2023-05-22 20:24 UTC
